use super::*;

#[test]
fn should_serialize_every_operation_and_counter_identifier_in_catalog_order() {
    let operation_catalog = [
        (
            PerformanceOperation::ArtifactValidation,
            "artifact_validation",
        ),
        (
            PerformanceOperation::TokenizerInitialization,
            "tokenizer_initialization",
        ),
        (
            PerformanceOperation::MlxRuntimeInitialization,
            "mlx_runtime_initialization",
        ),
        (
            PerformanceOperation::ModelSafetensorsMapping,
            "model_safetensors_mapping",
        ),
        (
            PerformanceOperation::ModelTensorBinding,
            "model_tensor_binding",
        ),
        (
            PerformanceOperation::ExpertPagerPlanConstruction,
            "expert_pager_plan_construction",
        ),
        (
            PerformanceOperation::ResidentWeightMaterializationSynchronizationWait,
            "resident_weight_materialization_synchronization_wait",
        ),
        (
            PerformanceOperation::PersistentPromptCacheOpenAndScan,
            "persistent_prompt_cache_open_and_scan",
        ),
        (
            PerformanceOperation::ChatCommandValidation,
            "chat_command_validation",
        ),
        (
            PerformanceOperation::ImagePreprocessing,
            "image_preprocessing",
        ),
        (
            PerformanceOperation::VisionEmbeddingGraphConstruction,
            "vision_embedding_graph_construction",
        ),
        (
            PerformanceOperation::VisionEmbeddingEvaluationSynchronizationWait,
            "vision_embedding_evaluation_synchronization_wait",
        ),
        (PerformanceOperation::PromptRendering, "prompt_rendering"),
        (
            PerformanceOperation::PromptTokenization,
            "prompt_tokenization",
        ),
        (
            PerformanceOperation::GenerationOutputDecoderInitialization,
            "generation_output_decoder_initialization",
        ),
        (
            PerformanceOperation::MemoryAdmissionSnapshot,
            "memory_admission_snapshot",
        ),
        (
            PerformanceOperation::AdaptiveRamGrowthMemoryAdmission,
            "adaptive_ram_growth_memory_admission",
        ),
        (
            PerformanceOperation::LinearAttentionGraphConstruction,
            "linear_attention_graph_construction",
        ),
        (
            PerformanceOperation::FullAttentionGraphConstruction,
            "full_attention_graph_construction",
        ),
        (
            PerformanceOperation::PersistentPromptCachePrefixLookup,
            "persistent_prompt_cache_prefix_lookup",
        ),
        (
            PerformanceOperation::PersistentPromptCacheKvBlockRead,
            "persistent_prompt_cache_kv_block_read",
        ),
        (
            PerformanceOperation::PersistentPromptCacheRecurrentSnapshotRead,
            "persistent_prompt_cache_recurrent_snapshot_read",
        ),
        (
            PerformanceOperation::PersistentPromptCacheStateReconstruction,
            "persistent_prompt_cache_state_reconstruction",
        ),
        (
            PerformanceOperation::PersistentPromptCacheStateMaterializationSynchronizationWait,
            "persistent_prompt_cache_state_materialization_synchronization_wait",
        ),
        (
            PerformanceOperation::PersistentPromptCacheStateExtraction,
            "persistent_prompt_cache_state_extraction",
        ),
        (
            PerformanceOperation::PersistentPromptCacheKvBlockSerialization,
            "persistent_prompt_cache_kv_block_serialization",
        ),
        (
            PerformanceOperation::PersistentPromptCacheRecurrentSnapshotSerialization,
            "persistent_prompt_cache_recurrent_snapshot_serialization",
        ),
        (
            PerformanceOperation::PersistentPromptCacheRetentionCleanup,
            "persistent_prompt_cache_retention_cleanup",
        ),
        (
            PerformanceOperation::ExpertPageManifestConstruction,
            "expert_page_manifest_construction",
        ),
        (
            PerformanceOperation::ExpertPageMemoryBudgetSnapshot,
            "expert_page_memory_budget_snapshot",
        ),
        (
            PerformanceOperation::PagedRouterGraphConstruction,
            "paged_router_graph_construction",
        ),
        (
            PerformanceOperation::SelectedExpertIdContiguousGraphConstruction,
            "selected_expert_id_contiguous_graph_construction",
        ),
        (
            PerformanceOperation::SelectedExpertIdEvaluationSynchronizationWait,
            "selected_expert_id_evaluation_synchronization_wait",
        ),
        (
            PerformanceOperation::SelectedExpertIdHostMemoryCopy,
            "selected_expert_id_host_memory_copy",
        ),
        (
            PerformanceOperation::ExpertWeightMemoryCacheLookup,
            "expert_weight_memory_cache_lookup",
        ),
        (
            PerformanceOperation::ExpertWeightMemoryCacheEviction,
            "expert_weight_memory_cache_eviction",
        ),
        (
            PerformanceOperation::PagedMoeGraphConstruction,
            "paged_moe_graph_construction",
        ),
        (
            PerformanceOperation::ResidentMoeGraphConstruction,
            "resident_moe_graph_construction",
        ),
        (
            PerformanceOperation::FinalLogitsGraphConstruction,
            "final_logits_graph_construction",
        ),
        (
            PerformanceOperation::TokenSamplingGraphConstruction,
            "token_sampling_graph_construction",
        ),
        (
            PerformanceOperation::MtpHeadForwardGraphConstruction,
            "mtp_head_forward_graph_construction",
        ),
        (
            PerformanceOperation::MtpHeadStateEvaluationSynchronizationWait,
            "mtp_head_state_evaluation_synchronization_wait",
        ),
        (
            PerformanceOperation::MtpTargetVerificationSynchronizationWait,
            "mtp_target_verification_synchronization_wait",
        ),
        (
            PerformanceOperation::MtpRejectedDraftReplaySynchronizationWait,
            "mtp_rejected_draft_replay_synchronization_wait",
        ),
        (
            PerformanceOperation::PrefillStateEvaluationSynchronizationWait,
            "prefill_state_evaluation_synchronization_wait",
        ),
        (
            PerformanceOperation::ExpertBoundedSafetensorsLazyPageConstruction,
            "expert_bounded_safetensors_lazy_page_construction",
        ),
        (
            PerformanceOperation::AlignedExpertPackMetalIoPageLoad,
            "aligned_expert_pack_metal_io_page_load",
        ),
        (
            PerformanceOperation::ExpertWeightMemoryCachePageAssemblyGraphConstruction,
            "expert_weight_memory_cache_page_assembly_graph_construction",
        ),
        (
            PerformanceOperation::ExpertPagingDiagnosticLogging,
            "expert_paging_diagnostic_logging",
        ),
        (
            PerformanceOperation::DecodeAsyncEvaluationSubmission,
            "decode_async_evaluation_submission",
        ),
        (
            PerformanceOperation::GeneratedTokenItemSynchronizationWait,
            "generated_token_item_synchronization_wait",
        ),
        (
            PerformanceOperation::CompletedForwardMemorySnapshot,
            "completed_forward_memory_snapshot",
        ),
        (
            PerformanceOperation::PromptPrefillAdvanceSpan,
            "prompt_prefill_advance_span",
        ),
        (
            PerformanceOperation::DecodeAdvanceSpan,
            "decode_advance_span",
        ),
        (
            PerformanceOperation::AttentionForwardSpan,
            "attention_forward_span",
        ),
        (PerformanceOperation::MlpForwardSpan, "mlp_forward_span"),
        (
            PerformanceOperation::MlxAllocatorCacheCleanup,
            "mlx_allocator_cache_cleanup",
        ),
        (
            PerformanceOperation::FinalizedMlxMemorySnapshot,
            "finalized_mlx_memory_snapshot",
        ),
    ];
    let counter_catalog = [
        (PerformanceCounter::PromptTokenCount, "prompt_token_count"),
        (
            PerformanceCounter::RestoredPersistentPromptCacheTokenCount,
            "restored_persistent_prompt_cache_token_count",
        ),
        (
            PerformanceCounter::GeneratedTokenCount,
            "generated_token_count",
        ),
        (
            PerformanceCounter::PrefillChunckCount,
            "prefill_chunck_count",
        ),
        (
            PerformanceCounter::ExpertWeightMemoryCacheHitCount,
            "expert_weight_memory_cache_hit_count",
        ),
        (
            PerformanceCounter::ExpertWeightMemoryCacheCompleteLayerHitCount,
            "expert_weight_memory_cache_complete_layer_hit_count",
        ),
        (
            PerformanceCounter::ExpertWeightMemoryCacheMissCount,
            "expert_weight_memory_cache_miss_count",
        ),
        (
            PerformanceCounter::ExpertWeightMemoryCacheEvictionCount,
            "expert_weight_memory_cache_eviction_count",
        ),
        (
            PerformanceCounter::ExpertWeightDiskPageLoadCount,
            "expert_weight_disk_page_load_count",
        ),
        (
            PerformanceCounter::ExpertWeightDiskBatchLoadCount,
            "expert_weight_disk_batch_load_count",
        ),
        (
            PerformanceCounter::ExpertPageLogicalPayloadBytes,
            "expert_page_logical_payload_bytes",
        ),
        (
            PerformanceCounter::AlignedExpertPackMetalIoPageLoadCount,
            "aligned_expert_pack_metal_io_page_load_count",
        ),
        (
            PerformanceCounter::AlignedExpertPackMetalIoLogicalPayloadBytes,
            "aligned_expert_pack_metal_io_logical_payload_bytes",
        ),
        (
            PerformanceCounter::ExpertSsdReadCallCount,
            "expert_ssd_read_call_count",
        ),
        (
            PerformanceCounter::ExpertSsdReadByteCount,
            "expert_ssd_read_byte_count",
        ),
        (
            PerformanceCounter::ExpertSsdReadElapsedNanoseconds,
            "expert_ssd_read_elapsed_nanoseconds",
        ),
        (
            PerformanceCounter::ExpertSsdReadMaximumElapsedNanoseconds,
            "expert_ssd_read_maximum_elapsed_nanoseconds",
        ),
        (
            PerformanceCounter::ExpertSsdReadFailureCount,
            "expert_ssd_read_failure_count",
        ),
        (
            PerformanceCounter::ExpertRoutePredictedExpertCount,
            "expert_route_predicted_expert_count",
        ),
        (
            PerformanceCounter::ExpertRouteMatchedExpertCount,
            "expert_route_matched_expert_count",
        ),
        (
            PerformanceCounter::ExpertRouteCompletelyMatchedLayerCount,
            "expert_route_completely_matched_layer_count",
        ),
        (
            PerformanceCounter::ExpertRouteExaminedLayerCount,
            "expert_route_examined_layer_count",
        ),
        (
            PerformanceCounter::MtpAdmittedAttemptCount,
            "mtp_admitted_attempt_count",
        ),
        (
            PerformanceCounter::MtpAcceptedDraftCount,
            "mtp_accepted_draft_count",
        ),
        (
            PerformanceCounter::MtpRejectedDraftCount,
            "mtp_rejected_draft_count",
        ),
        (
            PerformanceCounter::MtpOperationalFallbackCount,
            "mtp_operational_fallback_count",
        ),
    ];
    let mut performance_attribution = PerformanceAttribution::enabled();
    for (operation_index, (performance_operation, _operation_identifier)) in
        operation_catalog.iter().enumerate()
    {
        let started_offset_nanoseconds = operation_index as u64 * 20;
        performance_attribution.record_completed_operation(
            *performance_operation,
            std::time::Duration::from_nanos(started_offset_nanoseconds),
            std::time::Duration::from_nanos(started_offset_nanoseconds + 10),
        );
    }
    for (performance_counter, _counter_identifier) in counter_catalog {
        performance_attribution.record_counter(performance_counter, 1);
    }

    let performance_attribution_json = serialize_generation_report(
        performance_attribution,
        PerformanceAttributionOutcome::Success,
    );
    let serialized_operation_identifiers = performance_attribution_json["operations"]
        .as_array()
        .expect("operations should serialize as an array")
        .iter()
        .filter_map(|operation_report| operation_report["operation"].as_str())
        .collect::<Vec<_>>();
    let serialized_counter_identifiers = performance_attribution_json["counters"]
        .as_array()
        .expect("counters should serialize as an array")
        .iter()
        .filter_map(|counter_report| counter_report["counter"].as_str())
        .collect::<Vec<_>>();

    assert_eq!(
        serialized_operation_identifiers,
        operation_catalog
            .iter()
            .map(|(_performance_operation, operation_identifier)| *operation_identifier)
            .collect::<Vec<_>>()
    );
    assert_eq!(
        serialized_counter_identifiers,
        counter_catalog
            .iter()
            .map(|(_performance_counter, counter_identifier)| *counter_identifier)
            .collect::<Vec<_>>()
    );
}
