use super::*;

#[test]
fn should_serialize_every_operation_and_counter_identifier_in_catalog_order() {
    let operation_catalog = [
        (
            PerformanceOperation::ArtifactValidation,
            "artifact_validation",
        ),
        (
            PerformanceOperation::StandaloneMtpArtifactValidation,
            "standalone_mtp_artifact_validation",
        ),
        (
            PerformanceOperation::MtpPairingCompatibilityValidation,
            "mtp_pairing_compatibility_validation",
        ),
        (
            PerformanceOperation::TokenizerInitialization,
            "tokenizer_initialization",
        ),
        (
            PerformanceOperation::MlxRuntimeInitialization,
            "mlx_runtime_initialization",
        ),
        (
            PerformanceOperation::ModelSafetensorsMapping,
            "model_safetensors_mapping",
        ),
        (
            PerformanceOperation::ModelTensorBinding,
            "model_tensor_binding",
        ),
        (
            PerformanceOperation::StandaloneMtpTensorBinding,
            "standalone_mtp_tensor_binding",
        ),
        (
            PerformanceOperation::StandaloneMtpMaterializationSynchronizationWait,
            "standalone_mtp_materialization_synchronization_wait",
        ),
        (
            PerformanceOperation::ExpertPagerPlanConstruction,
            "expert_pager_plan_construction",
        ),
        (
            PerformanceOperation::ResidentWeightMaterializationSynchronizationWait,
            "resident_weight_materialization_synchronization_wait",
        ),
        (
            PerformanceOperation::PersistentPromptCacheOpenAndScan,
            "persistent_prompt_cache_open_and_scan",
        ),
        (
            PerformanceOperation::ChatCommandValidation,
            "chat_command_validation",
        ),
        (
            PerformanceOperation::ImagePreprocessing,
            "image_preprocessing",
        ),
        (
            PerformanceOperation::VisionEmbeddingGraphConstruction,
            "vision_embedding_graph_construction",
        ),
        (
            PerformanceOperation::VisionEmbeddingEvaluationSynchronizationWait,
            "vision_embedding_evaluation_synchronization_wait",
        ),
        (PerformanceOperation::PromptRendering, "prompt_rendering"),
        (
            PerformanceOperation::PromptTokenization,
            "prompt_tokenization",
        ),
        (
            PerformanceOperation::GenerationOutputDecoderInitialization,
            "generation_output_decoder_initialization",
        ),
        (
            PerformanceOperation::MemoryAdmissionSnapshot,
            "memory_admission_snapshot",
        ),
        (
            PerformanceOperation::AdaptiveRamGrowthMemoryAdmission,
            "adaptive_ram_growth_memory_admission",
        ),
        (
            PerformanceOperation::LinearAttentionGraphConstruction,
            "linear_attention_graph_construction",
        ),
        (
            PerformanceOperation::FullAttentionGraphConstruction,
            "full_attention_graph_construction",
        ),
        (
            PerformanceOperation::PersistentPromptCachePrefixLookup,
            "persistent_prompt_cache_prefix_lookup",
        ),
        (
            PerformanceOperation::PersistentPromptCacheKvBlockRead,
            "persistent_prompt_cache_kv_block_read",
        ),
        (
            PerformanceOperation::PersistentPromptCacheRecurrentSnapshotRead,
            "persistent_prompt_cache_recurrent_snapshot_read",
        ),
        (
            PerformanceOperation::PersistentPromptCacheStateReconstruction,
            "persistent_prompt_cache_state_reconstruction",
        ),
        (
            PerformanceOperation::PersistentPromptCacheStateMaterializationSynchronizationWait,
            "persistent_prompt_cache_state_materialization_synchronization_wait",
        ),
        (
            PerformanceOperation::PersistentPromptCacheStateExtraction,
            "persistent_prompt_cache_state_extraction",
        ),
        (
            PerformanceOperation::PersistentPromptCacheKvBlockSerialization,
            "persistent_prompt_cache_kv_block_serialization",
        ),
        (
            PerformanceOperation::PersistentPromptCacheRecurrentSnapshotSerialization,
            "persistent_prompt_cache_recurrent_snapshot_serialization",
        ),
        (
            PerformanceOperation::PersistentPromptCacheRetentionCleanup,
            "persistent_prompt_cache_retention_cleanup",
        ),
        (
            PerformanceOperation::PagedRouterGraphConstruction,
            "paged_router_graph_construction",
        ),
        (
            PerformanceOperation::RetainedExpertPagePlanning,
            "retained_expert_page_planning",
        ),
        (
            PerformanceOperation::RustExpertStreamingLayerPreparation,
            "rust_expert_streaming_layer_preparation",
        ),
        (
            PerformanceOperation::ExpertRetentionReclamation,
            "expert_retention_reclamation",
        ),
        (
            PerformanceOperation::PagedMoeGraphConstruction,
            "paged_moe_graph_construction",
        ),
        (
            PerformanceOperation::ResidentMoeGraphConstruction,
            "resident_moe_graph_construction",
        ),
        (
            PerformanceOperation::FinalLogitsGraphConstruction,
            "final_logits_graph_construction",
        ),
        (
            PerformanceOperation::SpeculativePrefillDraftVisionEmbeddingGraphConstruction,
            "speculative_prefill_draft_vision_embedding_graph_construction",
        ),
        (
            PerformanceOperation::SpeculativePrefillDraftVisionEmbeddingEvaluationSynchronizationWait,
            "speculative_prefill_draft_vision_embedding_evaluation_synchronization_wait",
        ),
        (
            PerformanceOperation::TokenSamplingGraphConstruction,
            "token_sampling_graph_construction",
        ),
        (
            PerformanceOperation::MtpHeadForwardGraphConstruction,
            "mtp_head_forward_graph_construction",
        ),
        (
            PerformanceOperation::MtpHeadStateEvaluationSynchronizationWait,
            "mtp_head_state_evaluation_synchronization_wait",
        ),
        (
            PerformanceOperation::MtpPromptHistoryInitializationSpan,
            "mtp_prompt_history_initialization_span",
        ),
        (
            PerformanceOperation::MtpTargetVerificationSynchronizationWait,
            "mtp_target_verification_synchronization_wait",
        ),
        (
            PerformanceOperation::MtpRejectedDraftStateRestoration,
            "mtp_rejected_draft_state_restoration",
        ),
        (PerformanceOperation::MtpTargetRepair, "mtp_target_repair"),
        (
            PerformanceOperation::MtpPredictorCommitReplay,
            "mtp_predictor_commit_replay",
        ),
        (
            PerformanceOperation::MtpQueuedFrontierRestoration,
            "mtp_queued_frontier_restoration",
        ),
        (
            PerformanceOperation::MtpRequestStateCleanup,
            "mtp_request_state_cleanup",
        ),
        (
            PerformanceOperation::PrefillStateAsyncEvaluationSubmission,
            "prefill_state_async_evaluation_submission",
        ),
        (
            PerformanceOperation::PrefillStateGraphicsProcessorCompletionWait,
            "prefill_state_graphics_processor_completion_wait",
        ),
        (
            PerformanceOperation::ExpertPagingDiagnosticLogging,
            "expert_paging_diagnostic_logging",
        ),
        (
            PerformanceOperation::DecodeAsyncEvaluationSubmission,
            "decode_async_evaluation_submission",
        ),
        (
            PerformanceOperation::GeneratedTokenItemSynchronizationWait,
            "generated_token_item_synchronization_wait",
        ),
        (
            PerformanceOperation::CompletedForwardMemorySnapshot,
            "completed_forward_memory_snapshot",
        ),
        (
            PerformanceOperation::PromptPrefillAdvanceSpan,
            "prompt_prefill_advance_span",
        ),
        (
            PerformanceOperation::DecodeAdvanceSpan,
            "decode_advance_span",
        ),
        (
            PerformanceOperation::AttentionForwardSpan,
            "attention_forward_span",
        ),
        (PerformanceOperation::MlpForwardSpan, "mlp_forward_span"),
        (
            PerformanceOperation::MlxAllocatorCacheCleanup,
            "mlx_allocator_cache_cleanup",
        ),
        (
            PerformanceOperation::FinalizedMlxMemorySnapshot,
            "finalized_mlx_memory_snapshot",
        ),
    ];
    let counter_catalog = [
        (PerformanceCounter::PromptTokenCount, "prompt_token_count"),
        (
            PerformanceCounter::RestoredPersistentPromptCacheTokenCount,
            "restored_persistent_prompt_cache_token_count",
        ),
        (
            PerformanceCounter::GeneratedTokenCount,
            "generated_token_count",
        ),
        (
            PerformanceCounter::PrefillChunckCount,
            "prefill_chunck_count",
        ),
        (
            PerformanceCounter::PrefillCapacityRejectionCount,
            "prefill_capacity_rejection_count",
        ),
        (
            PerformanceCounter::PrefillCapacityRetryCount,
            "prefill_capacity_retry_count",
        ),
        (
            PerformanceCounter::RustExpertStreamingPayloadByteCount,
            "rust_expert_streaming_payload_byte_count",
        ),
        (
            PerformanceCounter::RustStreamedExpertProjectionGraphCount,
            "rust_streamed_expert_projection_graph_count",
        ),
        (
            PerformanceCounter::PositionalFileReadCallCount,
            "positional_file_read_call_count",
        ),
        (
            PerformanceCounter::PositionalFileReadByteCount,
            "positional_file_read_byte_count",
        ),
        (
            PerformanceCounter::PositionalFileReadElapsedNanoseconds,
            "positional_file_read_elapsed_nanoseconds",
        ),
        (
            PerformanceCounter::PositionalFileReadMaximumElapsedNanoseconds,
            "positional_file_read_maximum_elapsed_nanoseconds",
        ),
        (
            PerformanceCounter::PositionalFileReadMaximumConcurrentCount,
            "positional_file_read_maximum_concurrent_count",
        ),
        (
            PerformanceCounter::PositionalFileReadFailureCount,
            "positional_file_read_failure_count",
        ),
        (
            PerformanceCounter::ExpertRoutePredictedExpertCount,
            "expert_route_predicted_expert_count",
        ),
        (
            PerformanceCounter::ExpertRouteMatchedExpertCount,
            "expert_route_matched_expert_count",
        ),
        (
            PerformanceCounter::ExpertRouteCompletelyMatchedLayerCount,
            "expert_route_completely_matched_layer_count",
        ),
        (
            PerformanceCounter::ExpertRouteExaminedLayerCount,
            "expert_route_examined_layer_count",
        ),
        (
            PerformanceCounter::MtpMemoryAdmissionFallbackCount,
            "mtp_memory_admission_fallback_count",
        ),
        (
            PerformanceCounter::MtpAdmittedAttemptCount,
            "mtp_admitted_attempt_count",
        ),
        (
            PerformanceCounter::SpeculativePrefillTargetOnlyPrefixChunckCount,
            "speculative_prefill_target_only_prefix_chunck_count",
        ),
        (
            PerformanceCounter::SpeculativePrefillTargetOnlyPrefixTokenCount,
            "speculative_prefill_target_only_prefix_token_count",
        ),
        (
            PerformanceCounter::SpeculativePrefillTerminalCaptureChunckCount,
            "speculative_prefill_terminal_capture_chunck_count",
        ),
        (
            PerformanceCounter::SpeculativePrefillTerminalMtpHistoryTokenCount,
            "speculative_prefill_terminal_mtp_history_token_count",
        ),
        (
            PerformanceCounter::SpeculativePrefillMandatoryVisualTokenCount,
            "speculative_prefill_mandatory_visual_token_count",
        ),
        (
            PerformanceCounter::MtpPromptHistoryInitializationFallbackCount,
            "mtp_prompt_history_initialization_fallback_count",
        ),
        (
            PerformanceCounter::MtpFeedbackHistoryReseedCount,
            "mtp_feedback_history_reseed_count",
        ),
        (
            PerformanceCounter::MtpAcceptedDraftCount,
            "mtp_accepted_draft_count",
        ),
        (
            PerformanceCounter::MtpRejectedDraftCount,
            "mtp_rejected_draft_count",
        ),
        (
            PerformanceCounter::MtpRequestedDepthTotal,
            "mtp_requested_depth_total",
        ),
        (
            PerformanceCounter::MtpEffectiveDepthTotal,
            "mtp_effective_depth_total",
        ),
        (
            PerformanceCounter::MtpProposedDraftCount,
            "mtp_proposed_draft_count",
        ),
        (
            PerformanceCounter::MtpProposedDraftPositionOneCount,
            "mtp_proposed_draft_position_one_count",
        ),
        (
            PerformanceCounter::MtpProposedDraftPositionTwoCount,
            "mtp_proposed_draft_position_two_count",
        ),
        (
            PerformanceCounter::MtpProposedDraftPositionThreeCount,
            "mtp_proposed_draft_position_three_count",
        ),
        (
            PerformanceCounter::MtpAcceptedDraftPositionOneCount,
            "mtp_accepted_draft_position_one_count",
        ),
        (
            PerformanceCounter::MtpAcceptedDraftPositionTwoCount,
            "mtp_accepted_draft_position_two_count",
        ),
        (
            PerformanceCounter::MtpAcceptedDraftPositionThreeCount,
            "mtp_accepted_draft_position_three_count",
        ),
        (
            PerformanceCounter::MtpRejectedDraftPositionOneCount,
            "mtp_rejected_draft_position_one_count",
        ),
        (
            PerformanceCounter::MtpRejectedDraftPositionTwoCount,
            "mtp_rejected_draft_position_two_count",
        ),
        (
            PerformanceCounter::MtpRejectedDraftPositionThreeCount,
            "mtp_rejected_draft_position_three_count",
        ),
        (
            PerformanceCounter::MtpEosTruncatedPrefixCount,
            "mtp_eos_truncated_prefix_count",
        ),
        (
            PerformanceCounter::MtpOutputDepthDowngradeCount,
            "mtp_output_depth_downgrade_count",
        ),
        (
            PerformanceCounter::MtpContextDepthDowngradeCount,
            "mtp_context_depth_downgrade_count",
        ),
        (
            PerformanceCounter::MtpThinkingDepthDowngradeCount,
            "mtp_thinking_depth_downgrade_count",
        ),
        (
            PerformanceCounter::MtpMemoryDepthDowngradeCount,
            "mtp_memory_depth_downgrade_count",
        ),
        (
            PerformanceCounter::MtpVerificationWorkspaceByteCount,
            "mtp_verification_workspace_byte_count",
        ),
        (
            PerformanceCounter::MtpBoundarySnapshotByteCount,
            "mtp_boundary_snapshot_byte_count",
        ),
        (
            PerformanceCounter::MtpPersistentGrowthByteCount,
            "mtp_persistent_growth_byte_count",
        ),
        (
            PerformanceCounter::MtpTargetRepairCount,
            "mtp_target_repair_count",
        ),
        (
            PerformanceCounter::MtpPredictorReplayTokenCount,
            "mtp_predictor_replay_token_count",
        ),
        (
            PerformanceCounter::MtpQueuedFrontierRestorationCount,
            "mtp_queued_frontier_restoration_count",
        ),
        (
            PerformanceCounter::MtpCancellationWithQueuedStateCount,
            "mtp_cancellation_with_queued_state_count",
        ),
        (
            PerformanceCounter::MtpRequestTargetOnlyFallbackCount,
            "mtp_request_target_only_fallback_count",
        ),
        (
            PerformanceCounter::MtpOperationalFallbackCount,
            "mtp_operational_fallback_count",
        ),
    ];
    let mut performance_attribution = PerformanceAttribution::enabled();
    for (operation_index, (performance_operation, _operation_identifier)) in
        operation_catalog.iter().enumerate()
    {
        let started_offset_nanoseconds = operation_index as u64 * 20;
        performance_attribution.record_completed_operation(
            *performance_operation,
            std::time::Duration::from_nanos(started_offset_nanoseconds),
            std::time::Duration::from_nanos(started_offset_nanoseconds + 10),
        );
    }
    for (performance_counter, _counter_identifier) in counter_catalog {
        performance_attribution.record_counter(performance_counter, 1);
    }

    let performance_attribution_json = serialize_generation_report(
        performance_attribution,
        PerformanceAttributionOutcome::Success,
    );
    let serialized_operation_identifiers = performance_attribution_json["operations"]
        .as_array()
        .expect("operations should serialize as an array")
        .iter()
        .filter_map(|operation_report| operation_report["operation"].as_str())
        .collect::<Vec<_>>();
    let serialized_counter_identifiers = performance_attribution_json["counters"]
        .as_array()
        .expect("counters should serialize as an array")
        .iter()
        .filter_map(|counter_report| counter_report["counter"].as_str())
        .collect::<Vec<_>>();

    assert_eq!(
        serialized_operation_identifiers,
        operation_catalog
            .iter()
            .map(|(_performance_operation, operation_identifier)| *operation_identifier)
            .collect::<Vec<_>>()
    );
    assert_eq!(
        serialized_counter_identifiers,
        counter_catalog
            .iter()
            .map(|(_performance_counter, counter_identifier)| *counter_identifier)
            .collect::<Vec<_>>()
    );
}
