import DOMPurify from "dompurify";
import type { Config } from "dompurify";
import { ContentKey } from "./ContentKey";

/**
 * Mermaid emits its theme as a `<style>` block inside the SVG; without it the
 * node labels lose their colour and vanish against the node fills. That CSS is
 * generated by mermaid from the theme rather than from diagram text (which the
 * sanitiser has already reduced to text nodes), and its selectors are scoped to
 * this figure's id, so the worst a hostile diagram can do is restyle its own
 * figure. Scripts, foreign objects, and event handlers stay forbidden, and CSP
 * keeps any network side channel closed.
 */
const DIAGRAM_SVG_OPTIONS: Config = {
  USE_PROFILES: { svg: true, svgFilters: true },
  ADD_TAGS: ["style"],
  FORBID_TAGS: ["foreignObject", "script", "iframe", "use"],
  FORBID_ATTR: ["onerror", "onload", "onclick"],
};

/**
 * Diagrams (mermaid).
 *
 * A fenced ```mermaid block becomes a figure once its message has finished
 * streaming. The SVG mermaid produces is a whole document — its theme CSS, its
 * shapes, its text — so it is sanitised with an SVG-profile pass that is wider
 * than the markdown allowlist but still forbids anything that executes or embeds
 * markup. A diagram that cannot render keeps its source visible rather than
 * disappearing.
 */
export class DiagramPipeline {
  private readonly diagramCache = new Map<string, string>();
  private mermaidInitialised = false;

  /** Renders every diagram in one finished message. Finished SVGs are cached by
   * content key so a later re-render of the same message re-installs them
   * synchronously instead of parsing mermaid again. */
  public render(root: ParentNode): void {
    const mermaid = window.mermaid;
    if (!mermaid) {
      return;
    }
    this.initializeMermaid();
    const diagramBlocks = root.querySelectorAll("pre > code.language-mermaid");
    diagramBlocks.forEach((diagramBlock) => {
      const pre = diagramBlock.parentElement;
      const codeBlockWrapper = pre ? pre.parentElement : null;
      if (!codeBlockWrapper || !codeBlockWrapper.classList.contains("code-block")) {
        return;
      }
      const renderState = (diagramBlock as HTMLElement).dataset.diagram;
      if (renderState === "true" || renderState === "failed" || renderState === "pending") {
        return;
      }
      const diagramSource = diagramBlock.textContent ?? "";
      const cacheKey = `diagram-${ContentKey.hash(diagramSource)}`;
      const cachedSvg = this.diagramCache.get(cacheKey);
      if (cachedSvg !== undefined) {
        DiagramPipeline.installFigure(codeBlockWrapper, cachedSvg);
        (diagramBlock as HTMLElement).dataset.diagram = "true";
        return;
      }
      (diagramBlock as HTMLElement).dataset.diagram = "pending";
      mermaid
        .render(cacheKey, diagramSource)
        .then((renderResult) => {
          if (!renderResult || !renderResult.svg) {
            throw new Error("mermaid produced no svg");
          }
          // The strict config keeps the plain-string overload of sanitize.
          const sanitisedSvg = DOMPurify.sanitize(renderResult.svg, DIAGRAM_SVG_OPTIONS);
          if (sanitisedSvg.indexOf("<svg") === -1) {
            throw new Error("diagram svg did not survive sanitisation");
          }
          this.diagramCache.set(cacheKey, sanitisedSvg);
          if (codeBlockWrapper.isConnected) {
            DiagramPipeline.installFigure(codeBlockWrapper, sanitisedSvg);
          }
        })
        .catch(() => {
          // A diagram that cannot render keeps its source readable, the same way a
          // markdown fragment that cannot finish mid-stream stays visible.
          (diagramBlock as HTMLElement).dataset.diagram = "failed";
          if (codeBlockWrapper.isConnected) {
            codeBlockWrapper.classList.add("code-block--diagram-failed");
          }
        });
    });
  }

  private initializeMermaid(): void {
    const mermaid = window.mermaid;
    if (!mermaid || this.mermaidInitialised) {
      return;
    }
    mermaid.initialize({
      startOnLoad: false,
      securityLevel: "strict",
      theme: "dark",
      // Mermaid labels flowcharts as HTML inside <foreignObject> by default, which
      // the SVG sanitiser forbids outright because it can carry arbitrary markup.
      // BOTH keys are required: measured in this shell, the flowchart key alone
      // still produced foreignObject, while both together produced native SVG
      // <text> labels that survive the strict list and stay readable.
      htmlLabels: false,
      flowchart: { htmlLabels: false },
      logLevel: 0,
    });
    this.mermaidInitialised = true;
  }

  /** Replaces the fenced source with the rendered figure, keeping the block key. */
  private static installFigure(codeBlockWrapper: HTMLElement, sanitisedSvg: string): void {
    const figure = document.createElement("figure");
    figure.className = "diagram";
    figure.innerHTML = sanitisedSvg;
    codeBlockWrapper.innerHTML = "";
    codeBlockWrapper.appendChild(figure);
    codeBlockWrapper.classList.add("code-block--diagram");
  }
}
