#!/usr/bin/env sh

set -eu

readonly MAXIMUM_SOURCE_LINES=550
readonly WARNING_SOURCE_LINES=500
readonly MAXIMUM_STAGED_SOURCE_LINES=600
readonly MAXIMUM_ELAPSED_SECONDS=120

SOURCE_SIZE_ROOT=""
TEMPORARY_DIRECTORY=""

cleanup() {
    case "${TEMPORARY_DIRECTORY:-}" in
        ""|/|.|..)
            return
            ;;
    esac
    if [ -d "${TEMPORARY_DIRECTORY}" ]; then
        rm -rf "${TEMPORARY_DIRECTORY}"
    fi
}
trap cleanup 0

elapsed_seconds() {
    current_epoch_seconds="$(date +%s)"
    printf '%s' "$((current_epoch_seconds - started_epoch_seconds))"
}

assert_within_timeout() {
    if [ "$(elapsed_seconds)" -gt "${MAXIMUM_ELAPSED_SECONDS}" ]; then
        printf '%s\n' "[source-size] status=failed reason=timeout limit_seconds=${MAXIMUM_ELAPSED_SECONDS}" >&2
        exit 1
    fi
}

report_progress() {
    progress_completed_source_file_count="$1"
    progress_total_source_file_count="$2"
    progress_elapsed_seconds="$(elapsed_seconds)"
    if [ "${progress_total_source_file_count}" -eq 0 ]; then
        progress_percentage=100
        progress_eta_seconds=0
    else
        progress_percentage=$((progress_completed_source_file_count * 100 / progress_total_source_file_count))
        if [ "${progress_completed_source_file_count}" -eq 0 ] || [ "${progress_elapsed_seconds}" -eq 0 ]; then
            progress_eta_seconds=0
        else
            progress_estimated_total_seconds=$(((progress_elapsed_seconds * progress_total_source_file_count + progress_completed_source_file_count - 1) / progress_completed_source_file_count))
            progress_eta_seconds=$((progress_estimated_total_seconds - progress_elapsed_seconds))
        fi
    fi
    printf '%s\n' "[source-size] status=progress files=${progress_completed_source_file_count}/${progress_total_source_file_count} percentage=${progress_percentage} ETA_seconds=${progress_eta_seconds} elapsed_seconds=${progress_elapsed_seconds}"
}

is_deterministically_generated_binding() {
    source_file="$1"
    first_source_line=""
    IFS= read -r first_source_line < "${source_file}" || true
    case "${first_source_line}" in
        "// @generated"*|"/* @generated"*|"# @generated"*|"// automatically generated by rust-bindgen"*|"/* automatically generated by rust-bindgen"*|"# automatically generated by rust-bindgen"*)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

count_source_lines() {
    source_file="$1"
    source_line_count="$(sed -n '$=' "${source_file}")"
    printf '%s' "${source_line_count:-0}"
}

is_staged_source_file_path() {
    staged_source_file_path="$1"
    case "${staged_source_file_path}" in
        *.rs|*.py|*.sh|*.swift|*.c|*.cc|*.cpp|*.cxx|*.h|*.hh|*.hpp|*.hxx|*.m|*.mm|*.metal|*.js|*.jsx|*.ts|*.tsx)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

check_staged_source_file_sizes() {
    repository_root="$1"
    staged_path_manifest="${TEMPORARY_DIRECTORY}/staged-paths.txt"
    staged_source_blob_path="${TEMPORARY_DIRECTORY}/staged-source-blob"
    git -C "${repository_root}" diff --cached --name-only --diff-filter=ACMR > "${staged_path_manifest}"
    staged_path_count_text="$(wc -l < "${staged_path_manifest}")"
    staged_path_count=$((staged_path_count_text + 0))
    checked_staged_source_file_count=0
    failing_staged_source_file_count=0
    printf '%s\n' "[source-size] status=start mode=staged timeout_seconds=${MAXIMUM_ELAPSED_SECONDS} root=${repository_root}"

    while IFS= read -r staged_source_file_path || [ -n "${staged_source_file_path}" ]; do
        assert_within_timeout
        if ! is_staged_source_file_path "${staged_source_file_path}"; then
            continue
        fi
        checked_staged_source_file_count=$((checked_staged_source_file_count + 1))
        if ! git -C "${repository_root}" show ":${staged_source_file_path}" > "${staged_source_blob_path}"; then
            failing_staged_source_file_count=$((failing_staged_source_file_count + 1))
            printf '%s\n' "[source-size] status=failed reason=unreadable-staged-source path=${staged_source_file_path}" >&2
            continue
        fi
        if ! is_deterministically_generated_binding "${staged_source_blob_path}"; then
            staged_source_line_count="$(count_source_lines "${staged_source_blob_path}")"
            if [ "${staged_source_line_count}" -gt "${MAXIMUM_STAGED_SOURCE_LINES}" ]; then
                failing_staged_source_file_count=$((failing_staged_source_file_count + 1))
                printf '%s\n' "[source-size] status=failed lines=${staged_source_line_count} limit=${MAXIMUM_STAGED_SOURCE_LINES} path=${staged_source_file_path}"
            fi
        fi
        if [ $((checked_staged_source_file_count % 100)) -eq 0 ] || [ "${checked_staged_source_file_count}" -eq "${staged_path_count}" ]; then
            report_progress "${checked_staged_source_file_count}" "${staged_path_count}"
        fi
    done < "${staged_path_manifest}"

    if [ "${checked_staged_source_file_count}" -eq 0 ]; then
        report_progress 0 0
    fi
    if [ "${failing_staged_source_file_count}" -gt 0 ]; then
        printf '%s\n' "[source-size] status=failed mode=staged files=${failing_staged_source_file_count} elapsed_seconds=$(elapsed_seconds)"
        return 1
    fi
    printf '%s\n' "[source-size] status=success mode=staged files=${checked_staged_source_file_count} elapsed_seconds=$(elapsed_seconds)"
}

main() {
    case "${1:-}" in
        --staged)
            if [ "$#" -ne 1 ]; then
                printf '%s\n' '[source-size] status=failed reason=unexpected-staged-arguments' >&2
                exit 1
            fi
            SOURCE_SIZE_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
                printf '%s\n' '[source-size] status=failed reason=not-a-git-worktree' >&2
                exit 1
            }
            ;;
        "")
            SOURCE_SIZE_ROOT="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
            ;;
        *)
            if [ "$#" -ne 1 ]; then
                printf '%s\n' '[source-size] status=failed reason=unexpected-arguments' >&2
                exit 1
            fi
            SOURCE_SIZE_ROOT="$1"
            ;;
    esac
    if [ ! -d "${SOURCE_SIZE_ROOT}" ]; then
        printf '%s\n' "[source-size] status=failed reason=missing-root path=${SOURCE_SIZE_ROOT}" >&2
        exit 1
    fi

    started_epoch_seconds="$(date +%s)"
    TEMPORARY_DIRECTORY="$(mktemp -d)"
    if [ "${1:-}" = "--staged" ]; then
        check_staged_source_file_sizes "${SOURCE_SIZE_ROOT}"
        return
    fi
    source_manifest_path="${TEMPORARY_DIRECTORY}/rust-source-files.txt"
    printf '%s\n' "[source-size] status=start timeout_seconds=${MAXIMUM_ELAPSED_SECONDS} root=${SOURCE_SIZE_ROOT}"
    find "${SOURCE_SIZE_ROOT}" -type f -name '*.rs' ! -path '*/target/*' ! -path '*/tests/*' > "${source_manifest_path}"
    source_file_count_text="$(wc -l < "${source_manifest_path}")"
    source_file_count=$((source_file_count_text + 0))
    checked_source_file_count=0
    warning_source_file_count=0
    failing_source_file_count=0

    while IFS= read -r source_file; do
        assert_within_timeout
        checked_source_file_count=$((checked_source_file_count + 1))
        if ! is_deterministically_generated_binding "${source_file}"; then
            source_line_count="$(count_source_lines "${source_file}")"
            if [ "${source_line_count}" -gt "${MAXIMUM_SOURCE_LINES}" ]; then
                failing_source_file_count=$((failing_source_file_count + 1))
                printf '%s\n' "[source-size] status=failed lines=${source_line_count} limit=${MAXIMUM_SOURCE_LINES} path=${source_file}"
            elif [ "${source_line_count}" -gt "${WARNING_SOURCE_LINES}" ]; then
                warning_source_file_count=$((warning_source_file_count + 1))
                printf '%s\n' "[source-size] status=warning lines=${source_line_count} threshold=$((WARNING_SOURCE_LINES + 1)) path=${source_file}"
            fi
        fi
        if [ $((checked_source_file_count % 100)) -eq 0 ] || [ "${checked_source_file_count}" -eq "${source_file_count}" ]; then
            report_progress "${checked_source_file_count}" "${source_file_count}"
        fi
    done < "${source_manifest_path}"

    if [ "${source_file_count}" -eq 0 ]; then
        report_progress 0 0
    fi

    if [ "${failing_source_file_count}" -gt 0 ]; then
        printf '%s\n' "[source-size] status=failed files=${failing_source_file_count} warnings=${warning_source_file_count} elapsed_seconds=$(elapsed_seconds)"
        exit 1
    fi
    printf '%s\n' "[source-size] status=success files=${checked_source_file_count} warnings=${warning_source_file_count} elapsed_seconds=$(elapsed_seconds)"
}

main "$@"
